title: Ruminations
description: Digital sounding board. All views expressed are my own.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  LinkedIn: https://www.linkedin.com/in/ribhu-8848
